default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password:
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: <%= ENV['DB_HOST'] || 'localhost' %>
  database: studytube_task_development

test:
  <<: *default
  host: <%= ENV['DB_HOST'] || 'localhost' %>
  database: studytube_task_test

production:
  <<: *default
  database: studytube_task_production
  password: <%= ENV['STUDYTUBE_TASK_DATABASE_PASSWORD'] %>
